### ISSUE TITLE
Map load error when selecting AOI

### ISSUE THREAD

**Issue by Kinga-11** [sepal-contrib/sdg_15.3.1#126]
When I select AOI to run SDG 15.3.1 I have a javascript error, the map is not displayed, and further options are not enabled:

```
Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'LeafletMapModel' from module 'jupyter-leaflet'
Error: Module jupyter-leaflet, version ^0.16.0 is not registered, however,         0.17.3 is

    at T.loadClass (https://sepal.io/api/sandbox/jupyter/voila/static/3717.voila.js:1:76437)
    at T.loadModelClass (https://sepal.io/api/sandbox/jupyter/voila/static/3717.voila.js:1:73266)
    at T._make_model (https://sepal.io/api/sandbox/jupyter/voila/static/3717.voila.js:1:70054)
    at T.new_model (https://sepal.io/api/sandbox/jupyter/voila/static/3717.voila.js:1:67643)
    at https://sepal.io/api/sandbox/jupyter/voila/static/3717.voila.js:1:69828
    at Array.map ()
    at T._loadFromKernelModels (https://sepal.io/api/sandbox/jupyter/voila/static/3717.voila.js:1:69767)
    at async T.restoreWidgets (https://sepal.io/api/sandbox/jupyter/voila/static/3717.voila.js:1:77805)
```
    
In the console I have the following error:
```
Error: Module @jupyter-widgets/base, version ^1.2.0 is not registered, however,         2.0.0 is
    at T.loadClass (3717.voila.js:1:76437)
    at T.loadModelClass (3717.voila.js:1:73266)
    at T._make_model (3717.voila.js:1:70054)
    at T.new_model (3717.voila.js:1:67643)
    at 3717.voila.js:1:69828
    at Array.map (<anonymous>)
    at T._loadFromKernelModels (3717.voila.js:1:69767)
```
    
<img width="917" alt="Screenshot 2023-11-28 125745" src="https://github.com/sepal-contrib/sdg_15.3.1/assets/59577940/23cf3cfd-1be2-4b36-97b0-cbf9334003c9">

**Comment by dfguerrerom** [comment]
@Kinga-11 ,  this error has been already fixed, we are expecting to release a new version with the fix by the end of the week.
